# Generated by Django 3.1.3 on 2021-02-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210201_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='users',
        ),
    ]
