# Generated by Django 3.1.3 on 2021-02-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210205_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='users',
            new_name='user',
        ),
    ]
